# Generated by Django 2.2.19 on 2024-10-13 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='trips',
            name='end_point',
            field=models.ManyToManyField(related_name='end_point_trips', to='trip.Address', verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='trips',
            name='starting_point',
            field=models.ManyToManyField(related_name='starting_point_trips', to='trip.Address', verbose_name='Откуда'),
        ),
    ]
